### ISSUE TITLE
Issue combining Stackable Enchanting books with "Chest sorting" mods

### ISSUE THREAD

**Issue by Demadunk** [pajicadvance/cherry-on-top#1]
enableStackableEnchantedBooks in the cherry on top early.json being enabled will cause enchanting books to merge into one stack of a singular enchant book when it is used in a conjunction with a mod like TerraStorage's "sort chest" or "sort inventory" options. As such I'd recommend finding a way to distinctly seperate enchant books from their enchants or turning the option to off by default.

**Comment by Demadunk** [comment]
To make things clear, this will turn a group of 3 enchant books with different enchants into one stack of 3 books being duplicates of the first enchant book.

**Comment by pajicadvance** [comment]
Thanks for the report, can you link me the specific sorting mod(s) where this happens?

**Comment by pajicadvance** [comment]
For TerraStorage specifically, it looks like an issue on their end, because sorting containers doesn't seem to take item components into account from what I can see.

**Comment by Demadunk** [comment]
The mods I tested so far was TerraStorage and CleanContainers, here's the link to the other mod I tested before I disabled the config.
https://modrinth.com/mod/cleancontainer

**Comment by pajicadvance** [comment]
Yeah, this is not an issue on my side. The sorting algorithms in those mods need to also compare item components on the items when they exist, or else you get this kind of behavior that results in data loss.
